- name: Home server playbook
  hosts: localhost
  tasks:
    - name: Register user_id
      set_fact:
        user_id: "ariel"
    
    - name: Install awk
      become: True
      pacman:
        name: "awk"
        state: "present"

    - name: Get user home directory
      changed_when: false
      register: getent
      shell: "getent passwd {{ user_id }}  | awk -F: '{ print $6 }'"

    - name: Register user_id
      set_fact:
        user_home: "{{ getent.stdout }}"
    
    - name: Include XOrg task list
      include_tasks: ./roles/xorg.yaml
    
    - name: Include ZSH task list
      include_tasks: ./roles/zsh.yaml
    
    - name: Include OpenBox task list
      include_tasks: ./roles/openbox.yaml
    
    