---

- name: Ensure required packages are installed
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - zsh
    - zsh-autosuggestions
    - zsh-completions
    - zsh-syntax-highlighting


- name: Copy config files
  copy:
    dest: "{{ user_home }}/.config"
    group: "{{ user_id }}"
    mode: 0755
    owner: "{{ user_id }}"
    src: zsh-files/zsh

- name: Copy main config file
  copy:
    dest: "{{ user_home }}/.zshrc"
    group: "{{ user_id }}"
    mode: 0644
    owner: "{{ user_id }}"
    src: "zsh-files/.zshrc"

# - name: Create symbolic link to theme
#   file:
#     dest: "{{ user_home }}/.config/zsh/themes/default.zsh"
#     group: "{{ user_id }}"
#     owner: "{{ user_id }}"
#     src: "{{ user_home }}/.config/zsh/themes/{{ theme }}.zsh"
#     state: link